### ISSUE TITLE
1.2.1 Use Case Diagram

### ISSUE THREAD

**Issue by chococtea** [ICT2101-P3Team2/ICT2101_P3-2#11]
Create the Use Case diagram based on our requirements and post inside the google doc (ICT2101_Project)
https://docs.google.com/document/d/1XFdPDBnVtw4iGJHG2eWd7-VvjRx0cah2YoD-MH4rWQo/edit?usp=sharing

**Comment by chococtea** [comment]
Finalised the current Use Case Diagram. Can be found in the M1 Report or the lucidchart link in the google docs

**Comment by EllynnTeo** [comment]
![Image](https://user-images.githubusercontent.com/35196552/192013101-68acd766-dfb3-4378-a06d-a0603cc8ec93.png)
