### ISSUE TITLE
1.2.2 Use Case Description

### ISSUE THREAD

**Issue by chococtea** [ICT2101-P3Team2/ICT2101_P3-2#12]
Write up use-case descriptions based on our UML diagram and post inside the google doc (ICT2101_Project)
https://docs.google.com/document/d/1XFdPDBnVtw4iGJHG2eWd7-VvjRx0cah2YoD-MH4rWQo/edit?usp=sharing

**Comment by chococtea** [comment]
Finalised the current use case descriptions. Can be found in M1 Report Appendix A or the google docs link above

**Comment by EllynnTeo** [comment]
[2101_UseCaseDescriptions.pdf](https://github.com/ICT2101-P3Team2/ICT2101_P3-2/files/9635726/2101_UseCaseDescriptions.pdf)
