### ISSUE TITLE
2.3.1 - M2: Component Design

### ISSUE THREAD

**Issue by EllynnTeo** [ICT2101-P3Team2/ICT2101_P3-2#17]
Create Component Diagram at [Component Diagram](https://lucid.app/lucidchart/2f0fb5c0-bf11-4cd5-9f32-40a5fa7660d2/edit?invitationId=inv_69f6e902-e76c-4a2a-9960-596f70dde6f1&page=mIOZfrDSutKj#)

**Comment by YUyou0** [comment]
![Image](https://user-images.githubusercontent.com/45277234/197336459-2dadbc04-eb02-4562-b745-97ae21892ab2.png)

**Comment by EllynnTeo** [comment]
Reopened to add more details to the diagram

**Comment by chococtea** [comment]
![Image](https://user-images.githubusercontent.com/92836838/198556756-56011c8e-8ee8-46f0-9f7e-0842b6ef4628.png)

**Comment by EllynnTeo** [comment]
Completed and added updated version to M2 report
