### ISSUE TITLE
2.4 - M2: Sequence Diagram

### ISSUE THREAD

**Issue by EllynnTeo** [ICT2101-P3Team2/ICT2101_P3-2#18]
Sequence Diagram can be found at [Sequence Diagram](https://lucid.app/lucidchart/2f0fb5c0-bf11-4cd5-9f32-40a5fa7660d2/edit?invitationId=inv_69f6e902-e76c-4a2a-9960-596f70dde6f1&page=4_41lrNdsnz9#)

**Comment by nicnathaniel** [comment]
completed SD 6,8,9,10 (19 Oct 2022)

**Comment by nicnathaniel** [comment]
Completed SD 1, 4, 11, 12, 20

**Comment by nicnathaniel** [comment]
selected SD placed into report
