### ISSUE TITLE
2.1.1 - M2: Client Review Meeting

### ISSUE THREAD

**Issue by chococtea** [ICT2101-P3Team2/ICT2101_P3-2#19]

**Comment by EllynnTeo** [comment]
[ICT2x01_M1__p3-2_Review_Comments.pdf](https://github.com/ICT2101-P3Team2/ICT2101_P3-2/files/9738450/ICT2x01_M1__p3-2_Review_Comments.pdf)

Comments from Review Meeting

**Comment by chococtea** [comment]
Things to modify:
1. FR & NFR
2. Use Case Diagram
3. Use Case Descriptions
4. UCP
