### ISSUE TITLE
2.7 - M2: M2 Documentation

### ISSUE THREAD

**Issue by EllynnTeo** [ICT2101-P3Team2/ICT2101_P3-2#23]
Information to be completed for M2 Report:
- [x] Introduction
- [x] Product Scope
- [x] Intended Audience
- [x] References
- [x] Specific Requirements (Changes from M1)
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/25
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/26
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/27
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/28
- [x] Architecture Design
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/33
- [x] Class Diagram
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/14
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/15
- [x] ECB Diagram
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/32
- [x] Component Diagram
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/17
- [x] Project Plan
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/29
- [x] Individual Reflections (Weiqi)
- [x] Individual Reflections (Nicholas)
- [x] Individual Reflections (Ellynn)
- [x] Individual Reflections (Sarah)
- [x] Appendix A - Use Case Descriptions
- [x] Appendix B - Overall Class Diagram
- [x] Appendix C - Data Dictinary

**Comment by chococtea** [comment]
Link to report: https://docs.google.com/document/d/1qFn-Y0L1ubIb3FtB5M3c_M2ZAoJSH8ldruniLONzYmg/edit?usp=sharing

Can find this link in slack too.

**Comment by chococtea** [comment]
Uploaded on xSite - 29/10/22
