### ISSUE TITLE
2.2.3 - M2: ECB Diagram

### ISSUE THREAD

**Issue by EllynnTeo** [ICT2101-P3Team2/ICT2101_P3-2#32]
Create ClassDiagram at [Class Diagram](https://lucid.app/lucidchart/2f0fb5c0-bf11-4cd5-9f32-40a5fa7660d2/edit?invitationId=inv_69f6e902-e76c-4a2a-9960-596f70dde6f1&page=YNoUS4LlHdP_#)

**Comment by EllynnTeo** [comment]
Expand class diagram to include control and boundary classes - 20 October 2022

**Comment by chococtea** [comment]
[2101_ECBDiagram.pdf](https://github.com/ICT2101-P3Team2/ICT2101_P3-2/files/9844838/2101_ECBDiagram.pdf)

Finalised by Ellynn & Sarah on 22/10/22.

**Comment by EllynnTeo** [comment]
Reopened to include interface classes

**Comment by chococtea** [comment]
[2101_ECBDiagram.pdf](https://github.com/ICT2101-P3Team2/ICT2101_P3-2/files/9887321/2101_ECBDiagram.pdf)

Latest Updated ECB Diagram
