### ISSUE TITLE
3.1 - M3: Client Review Meeting & Modifications

### ISSUE THREAD

**Issue by chococtea** [ICT2101-P3Team2/ICT2101_P3-2#36]
M2 Modification:

- [x] Modify Use Case Diagram
- [x] Modify Use Case Description
- [x] Modify Component Diagram
- [x] Modify Class/ ECB Diagram
- [x] Modify Sequence Diagrams

**Comment by chococtea** [comment]
![Image](https://user-images.githubusercontent.com/92836838/201101213-8aee95de-ddba-4677-89af-3eeb70091940.png)

Finalised the use case diagram on 10 Oct 22 by Sarah. [Task Duration: 10 Oct 22 - 10 Oct 22]

**Comment by EllynnTeo** [comment]
![Image](https://user-images.githubusercontent.com/35196552/202188141-04ad4b91-e067-41cd-a9f5-6d46caf8b37f.png)

Edited Component Diagram after M2 Review
Finalised Component Diagram, Done on 10 Oct 2022 By Ellynn

**Comment by nicnathaniel** [comment]
![Image](https://user-images.githubusercontent.com/94159228/202223053-f20e3a2a-f5da-490f-9c3f-651abdc6c7c7.png)



![Image](https://user-images.githubusercontent.com/94159228/202223188-58e5dac9-9072-444c-824a-fae19f621037.png)



![Image](https://user-images.githubusercontent.com/94159228/202223290-8583de0c-fa91-4284-b250-3fe45c64f943.png)



![Image](https://user-images.githubusercontent.com/94159228/202223443-869057e3-98c0-46bf-b63a-b31af8ff026d.png)

**Comment by EllynnTeo** [comment]
[ICT2101_Workload Management System Revised Class_ECB Diagrams.pdf](https://github.com/ICT2101-P3Team2/ICT2101_P3-2/files/10043150/ICT2101_Workload.Management.System.Revised.Class_ECB.Diagrams.pdf)

Finalised the Revised Class/ ECB Diagrams on 17 Nov 2022 by Ellynn & Sarah. [Task Duration: 10/11/22 - 17/11/22]
