### ISSUE TITLE
M3: Prototype

### ISSUE THREAD

**Issue by EllynnTeo** [ICT2101-P3Team2/ICT2101_P3-2#42]
Figma [Link](https://www.figma.com/file/pCzHpiw95c8xhlcUVF4axV/2101_Prototype?node-id=6%3A2) to Interactive Prototype
- [x] Staff Landing Page 
- [x] Staff Accept/ Reject Jobs Page
- [x] Staff Add/ Edit Availability & Preference Page
- [x] Manger Landing Page
- [x] IT Admin Page
- [x] Login
- [x] Video

**Comment by nicnathaniel** [comment]
Manager Landing Page done

**Comment by EllynnTeo** [comment]
Completed Staff Pages (Landing, Accept/ Reject Jobs, Add/ Edit Availability & Preference). Done by: Ellynn Duration: 18Nov - 25Nov (7 Days)

Staff Landing Page
![Image](https://user-images.githubusercontent.com/35196552/204075006-31bd7327-d5a4-4f58-9d72-68783a79a974.png)

Staff Accept/ Reject Job Page
![Image](https://user-images.githubusercontent.com/35196552/204075130-34e69010-2a70-4510-b762-c8db8ec0d0f7.png)

Add/ Edit Availability & Preference
![Image](https://user-images.githubusercontent.com/35196552/204075145-2876fb2c-c98d-48f4-8e22-a28c269a66d7.png)


![Image](https://user-images.githubusercontent.com/35196552/204075159-0bd44fec-4246-44cc-a1e2-bca45c7cc7aa.png)



![Image](https://user-images.githubusercontent.com/35196552/204075183-9f725959-b328-42ee-ae6d-10ea22bea146.png)

**Comment by chococtea** [comment]
**Login Page**
![Image](https://user-images.githubusercontent.com/92836838/204076861-cf9f964f-587f-47e2-9df8-aeb6d686fe2d.PNG)

**IT Admin Landing Page**
![Image](https://user-images.githubusercontent.com/92836838/204076863-f430f32e-6e41-46d3-a123-bb47e1c5a8d7.PNG)

**Create New Account Window Pop-up**
![Image](https://user-images.githubusercontent.com/92836838/204076870-45e9eff6-4ddf-4586-8fdd-5da9577db73d.PNG)

**Result after Create New Account**
![Image](https://user-images.githubusercontent.com/92836838/204076873-4ab596a5-d051-495a-b586-3ccc280a91e0.PNG)

**Find single account using search bar**
![Image](https://user-images.githubusercontent.com/92836838/204076886-ef96d5d0-7e06-4b95-b11a-acc4e47f4987.PNG)

**Delete Account Window Pop-up**
![Image](https://user-images.githubusercontent.com/92836838/204076875-a0b6d08e-3147-4bde-8e0e-7b711aedbb6b.PNG)

**Result from Delete Account**
![Image](https://user-images.githubusercontent.com/92836838/204076881-9b3170f8-d1c0-425e-a866-301a88bf6a59.PNG)

**View An Account Window Pop-up**
![Image](https://user-images.githubusercontent.com/92836838/204076890-02745c5e-2c7a-4f3e-b110-4ccb677f8982.PNG)

**Edit An Account Window Pop-up**
![Image](https://user-images.githubusercontent.com/92836838/204076893-a2d23cfc-94f7-4541-8703-5f72b0a6a5ee.PNG)

Finalised the prototype for login and it admin (landing page, create new account, delete an account, view an account & edit an account) by Sarah on 25/11/22. [Task duration: 17/11/22 - 25/11/22]

**Comment by chococtea** [comment]
Compiled the prototype demo into one video on 26/11/22 by Sarah. [Task Duration: 26/11/22 - 26/11/22]
