### ISSUE TITLE
M3: Wireframe

### ISSUE THREAD

**Issue by EllynnTeo** [ICT2101-P3Team2/ICT2101_P3-2#43]
Figma [Link ](https://www.figma.com/file/MqGbU5sxojLuVodQzh4a4z/2101_Wireframe?node-id=0%3A1) to Wireframe
- [x] Staff Landing Page
- [x] Manger Landing Page
- [x] IT Admin Page
- [x] Login

**Comment by chococtea** [comment]
**Wireframe for Staff Landing Page**
![Image](https://user-images.githubusercontent.com/92836838/202211174-50ecc239-a930-4d3a-96c6-2e2f6b70b4f0.jpg)

**Wireframe for Manager Landing Page**
![Image](https://user-images.githubusercontent.com/92836838/202211533-dc6a1f1d-30e7-4af5-923f-ff98bd4c83a6.jpg)

**Wireframe for IT Admin Landing Page**
![Image](https://user-images.githubusercontent.com/92836838/202211617-8eb9a533-81d5-4d58-badf-342a94512f87.jpg)

**Wireframe for Login Page**
![Image](https://user-images.githubusercontent.com/92836838/202211097-b68b4927-53ca-446f-9530-6eb43c12a0d6.jpg)

**Comment by chococtea** [comment]
Finalised the wireframes for all 4 pages mentioned above on 16 Nov 2022 by Sarah. [Task Duration: 15/11/22 - 16/11/22]
