### ISSUE TITLE
3.3 - M3: Whitebox Testing

### ISSUE THREAD

**Issue by EllynnTeo** [ICT2101-P3Team2/ICT2101_P3-2#44]
- [x] Write Pseudocode for 1 method
- [x] Create Control Flow Graph
- [x] Calculate Cyclomatic Complexity
- [x] Basis Path Testing
- [x] Write Test Case

**Comment by EllynnTeo** [comment]
Pusedocode
Function :
Allocate Jobs

1	allocateJobs()
2		if (selectedActivity == allocateJobs)
3			display upcoming jobs
4			select specifcJob
5			if (selectedJob == specificJob)
6				display staff availability
7				select staff
8				submit selection
9				confirm submission
10				if (submission == confirmed)
11					if (submissionTotal > maxRequired)
12						display errormessage
13						return
14					else if (submittedRole > maxARole)
15						display errormessage
16						return
17					else if (staffHours >= 40)
18						display errormessage
19						return
20					else
21						add to database
22						notify staff
23						display success message
24	end
					

Complete on 17 November 2022 by Sarah and Ellynn (Duration: 17 November 2022 - 17 November 2022 -> 1 Day)

**Comment by EllynnTeo** [comment]
![Image](https://user-images.githubusercontent.com/35196552/202732866-bd775879-384b-492f-9384-6fe2012ddc43.png)


![Image](https://user-images.githubusercontent.com/35196552/202733283-2cd64ff1-9c2c-4954-a256-9fddbe11f986.png)


Complete Control Flow Graph, Calculate Cyclomatic Complexity and Basis Path Testing  on 18 November 2022 by Ellynn (Duration: 18 November 2022 - 18 November 2022 -> 1 Day)

**Comment by chococtea** [comment]
![Image](https://user-images.githubusercontent.com/92836838/202740287-16430cef-3999-4f7f-87bf-bfc20997b071.png)
![Image](https://user-images.githubusercontent.com/92836838/202740534-1a4707a4-17e1-442e-bb77-a36abe0282f4.png)

Completed the test cases for white box testing on 18 Nov 2022 by Sarah. [Task Duration: 18/11/22 - 18/11/22]
