### ISSUE TITLE
3.2 - M3: Black-box Testing

### ISSUE THREAD

**Issue by EllynnTeo** [ICT2101-P3Team2/ICT2101_P3-2#45]
- [x] State Transition Diagram
- [x] Boundary Value Testing
- [x] Decision Table
- [x] Create Test Cases

**Comment by YUyou0** [comment]
- [ ] State Transition Diagram
- [ ] Test Specification
- [ ] Test Cases Creation
- [ ] Decision Table

**Comment by nicnathaniel** [comment]
Write completed test cases and decision tables
Duration: 24nov-25nov (1Day)


![Image](https://user-images.githubusercontent.com/94159228/204074345-bd09df6b-e09b-48b6-ae91-d0659222d180.png)



![Image](https://user-images.githubusercontent.com/94159228/204074354-281264c8-aec4-4aa7-a013-54cce5445d96.png)



![Image](https://user-images.githubusercontent.com/94159228/204074369-f5f894c4-5259-4331-850d-61a6edc85359.png)



![Image](https://user-images.githubusercontent.com/94159228/204074381-f49e9c59-11c0-459c-90ce-2c21b80bf8d0.png)



![Image](https://user-images.githubusercontent.com/94159228/204074395-41c40fea-f319-4657-8007-c1a64f7309d1.png)



![Image](https://user-images.githubusercontent.com/94159228/204074405-e71be081-5916-40d5-8315-67232a680922.png)

**Comment by EllynnTeo** [comment]
![Image](https://user-images.githubusercontent.com/35196552/204080853-78f62e95-9087-46a9-8d39-293a8899e8fb.png)

Completed state transition diagram
