### ISSUE TITLE
1.1.1 Questionnaires for Client Meeting - requirement specifications

### ISSUE THREAD

**Issue by nicnathaniel** [ICT2101-P3Team2/ICT2101_P3-2#8]
Questions posted inside the google doc (ICT2101_Project)
https://docs.google.com/document/d/1XFdPDBnVtw4iGJHG2eWd7-VvjRx0cah2YoD-MH4rWQo/edit?usp=sharing

**Comment by chococtea** [comment]
Finalised all the questions to be asked in the google docs
